"""fields_length_2

Revision ID: 1769636492
Revises: 1769636471
Create Date: 2026-01-28 21:41:33.011917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1769636492'
down_revision: Union[str, Sequence[str], None] = '1769636471'
branch_labels: Union[str, Sequence[str], None] = ()
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'gln',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=50),
               existing_comment='Global Location Number for the company HQ',
               existing_nullable=False)
    op.alter_column('devices', 'api_key_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    op.alter_column('plants', 'gln',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.String(length=31),
               existing_comment='GLN for this specific factory location',
               existing_nullable=False)
    op.alter_column('products', 'gtin',
               existing_type=sa.VARCHAR(length=14),
               type_=sa.String(length=31),
               existing_comment='Global Trade Item Number (14 digit)',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'gtin',
               existing_type=sa.String(length=31),
               type_=sa.VARCHAR(length=14),
               existing_comment='Global Trade Item Number (14 digit)',
               existing_nullable=False)
    op.alter_column('plants', 'gln',
               existing_type=sa.String(length=31),
               type_=sa.VARCHAR(length=13),
               existing_comment='GLN for this specific factory location',
               existing_nullable=False)
    op.alter_column('devices', 'api_key_hash',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    op.alter_column('companies', 'gln',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=13),
               existing_comment='Global Location Number for the company HQ',
               existing_nullable=False)
    # ### end Alembic commands ###
