"""init

Revision ID: 1769537220
Revises: 
Create Date: 2026-01-27 18:07:00.788036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1769537220'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = ('default',)
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gln', sa.String(length=13), nullable=False, comment='Global Location Number for the company HQ'),
    sa.Column('gcp', sa.String(length=20), nullable=False, comment='GS1 Company Prefix'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gln')
    )
    op.create_table('epcis_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('record_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_timezone_offset', sa.String(length=6), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('biz_step', sa.String(length=100), nullable=True),
    sa.Column('disposition', sa.String(length=100), nullable=True),
    sa.Column('read_point', sa.String(length=255), nullable=True),
    sa.Column('biz_location', sa.String(length=255), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_epcis_events_biz_step'), 'epcis_events', ['biz_step'], unique=False)
    op.create_index(op.f('ix_epcis_events_disposition'), 'epcis_events', ['disposition'], unique=False)
    op.create_index(op.f('ix_epcis_events_event_time'), 'epcis_events', ['event_time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('plants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gln', sa.String(length=13), nullable=False, comment='GLN for this specific factory location'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gln')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('gtin', sa.String(length=14), nullable=False, comment='Global Trade Item Number (14 digit)'),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gtin')
    )
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('plant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('device_role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('api_key_hash', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('epc_states',
    sa.Column('epc', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('current_biz_location', sa.String(length=255), nullable=True),
    sa.Column('current_disposition', sa.String(length=100), nullable=True),
    sa.Column('last_event_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('parent_epc', sa.String(length=255), nullable=True, comment='Immediate parent (e.g., Case EPC)'),
    sa.Column('top_level_epc', sa.String(length=255), nullable=True, comment='Topmost parent (e.g., Pallet EPC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('epc')
    )
    op.create_index(op.f('ix_epc_states_parent_epc'), 'epc_states', ['parent_epc'], unique=False)
    op.create_index(op.f('ix_epc_states_top_level_epc'), 'epc_states', ['top_level_epc'], unique=False)
    op.create_table('serial_counters',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('last_serial', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('serial_counters')
    op.drop_index(op.f('ix_epc_states_top_level_epc'), table_name='epc_states')
    op.drop_index(op.f('ix_epc_states_parent_epc'), table_name='epc_states')
    op.drop_table('epc_states')
    op.drop_table('devices')
    op.drop_table('products')
    op.drop_table('plants')
    op.drop_table('users')
    op.drop_index(op.f('ix_epcis_events_event_time'), table_name='epcis_events')
    op.drop_index(op.f('ix_epcis_events_disposition'), table_name='epcis_events')
    op.drop_index(op.f('ix_epcis_events_biz_step'), table_name='epcis_events')
    op.drop_table('epcis_events')
    op.drop_table('companies')
    # ### end Alembic commands ###
